'use strict';

/**
 * Invoice Line Item Builder
 *
 * Constructs the line items array and calculates totals for invoices.
 * CRITICAL: All arithmetic is integer paise. No floating-point operations.
 *
 * Exported functions:
 *   buildRenewalLineItems(subscription, planVersion)    → LineItem[]
 *   buildUpgradeLineItems(oldPlanVersion, newPlanVersion, proratedAmounts) → LineItem[]
 *   buildSeatLineItems(seatPrice, seatsAdded, daysRemaining) → LineItem[]
 *   calculateTotals(lineItems, taxRate)                → { subtotal, taxAmount, total }
 *
 * REF: docs/IMPLEMENTATION_ROADMAP.md §7.1 T4.3
 * REF: docs/DATABASE_DESIGN.md §7.2 — Line Items Generated by Proration
 */

/**
 * Build line items for a standard subscription renewal invoice.
 * Creates a single 'plan' line item covering the full billing period.
 *
 * @param {Object} subscription  - Subscription document
 * @param {Object} planVersion   - PlanVersion document (immutable snapshot)
 * @returns {Object[]} LineItem[]
 */
const buildRenewalLineItems = (subscription, planVersion) => {
  const periodStart = subscription.currentPeriodStart;
  const periodEnd   = subscription.currentPeriodEnd;

  const dateLabel = `${_formatDate(periodStart)} – ${_formatDate(periodEnd)}`;

  return [
    {
      description: `${planVersion.displayName} plan — ${dateLabel}`,
      quantity:    1,
      unitPrice:   planVersion.price,  // paise
      amount:      planVersion.price,  // paise; quantity(1) * unitPrice
      type:        'plan',
    },
  ];
};

/**
 * Build line items for a mid-cycle plan upgrade.
 * Creates two line items:
 *   1. proration_credit — refund for unused days on old plan (negative amount)
 *   2. proration_charge — cost for remaining days on new plan (positive amount)
 *
 * @param {Object} oldPlanVersion    - PlanVersion snapshot for the current plan
 * @param {Object} newPlanVersion    - PlanVersion snapshot for the target plan
 * @param {Object} proratedAmounts   - Result from calculateProration()
 * @param {number} proratedAmounts.creditAmount  - paise (refund for old plan)
 * @param {number} proratedAmounts.chargeAmount  - paise (cost for new plan)
 * @param {number} proratedAmounts.daysRemaining - number of days remaining in period
 * @returns {Object[]} LineItem[]
 */
const buildUpgradeLineItems = (oldPlanVersion, newPlanVersion, proratedAmounts) => {
  const { creditAmount, chargeAmount, daysRemaining } = proratedAmounts;

  return [
    {
      description: `${oldPlanVersion.displayName} plan — unused days (${daysRemaining} days)`,
      quantity:    1,
      unitPrice:   -creditAmount,   // Negative = credit applied
      amount:      -creditAmount,   // Negative amount reduces invoice total
      type:        'proration_credit',
    },
    {
      description: `${newPlanVersion.displayName} plan — remaining days (${daysRemaining} days)`,
      quantity:    1,
      unitPrice:   chargeAmount,
      amount:      chargeAmount,
      type:        'proration_charge',
    },
  ];
};

/**
 * Build a seat proration line item for adding seats mid-cycle.
 * Uses 30-day month convention for seat daily rate.
 *
 * @param {number} seatPrice      - Per-seat price in paise
 * @param {number} seatsAdded     - Number of new seats added
 * @param {number} daysRemaining  - Days remaining in current billing period
 * @returns {Object[]} LineItem[]
 */
const buildSeatLineItems = (seatPrice, seatsAdded, daysRemaining) => {
  // 30-day month convention for seat proration — simpler UX, standard SaaS
  const dailySeatRate = Math.round(seatPrice / 30);
  const chargeAmount  = dailySeatRate * daysRemaining * seatsAdded;

  return [
    {
      description: `Additional ${seatsAdded} seat${seatsAdded > 1 ? 's' : ''} — ${daysRemaining} days prorated`,
      quantity:    seatsAdded,
      unitPrice:   dailySeatRate * daysRemaining,   // Per-seat charge for remaining days
      amount:      chargeAmount,                    // Total for all seats
      type:        'seat',
    },
  ];
};

/**
 * Calculate invoice totals from line items.
 * CRITICAL: Integer arithmetic only. Math.round for tax to avoid sub-paise fractions.
 *
 * @param {Object[]} lineItems
 * @param {number}   taxRate    - Tax percentage (e.g. 18 for 18% GST)
 * @returns {{ subtotal: number, taxAmount: number, total: number }}
 */
const calculateTotals = (lineItems, taxRate = 18) => {
  // subtotal = sum of all line item amounts (can be negative if credits exceed charges)
  const subtotal = lineItems.reduce((sum, item) => sum + item.amount, 0);

  // Tax only on positive subtotal — no tax on refunds
  const taxableAmount = Math.max(0, subtotal);
  const taxAmount     = Math.round(taxableAmount * taxRate / 100);  // Integer paise

  const total = subtotal + taxAmount;

  return { subtotal, taxAmount, total };
};

// ── Helpers ───────────────────────────────────────────────────
const _formatDate = (date) => {
  if (!date) return '';
  const d = new Date(date);
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
};

module.exports = {
  buildRenewalLineItems,
  buildUpgradeLineItems,
  buildSeatLineItems,
  calculateTotals,
};
